version: '2.2'

services:
    webapp-client:
        build:
            context: client
            dockerfile: Dockerfile
            args:
                PORT: 8080
        image: myapp-client-img
        container_name: myapp_client
        ports:
            - "8080:8080"
        volumes:
            - ./client/:/usr/app
            - /usr/app/node_modules
        depends_on:
            - webapp-server
    webapp-server:
        env_file: server/.env
        build:
            context: server
            dockerfile: Dockerfile
                - PORT=8081
        image: myapp-server-img
        container_name: myapp_server
        volumes:
            - ./server/:/usr/app
            - /usr/app/node_modules
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        networks:
            - app-network
    mongo:
        image: mongo
        container_name: myapp-mongodb
        volumes:
            - data-volume:/data/db
        networks:
            - app-network
        ports:
            - "27017:27017"
volumes:
    data-volume:
    node_modules:
networks:
    app-network:
        driver: bridge
